
export const UserActionTypes = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER'
};
